dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    secure: HCxjwsBuUdfAAWOtDyLuDaVOXJG03bKibshHE+wrUbPBTwTFZci+cu5RYkUoj5VAmcciI3OQesw36QVnZesiMUouVRQOO4AGc4BpLDNdDhV0OpKqx3eEytrJeW139rQl5Ws/O2h2Phax3BvbZ6FIw2OWsYJxnkcGpv5fhg5YgDoOVt/92MzBNOVlngE1sJ91hpqVY8iqnN6pMlVEQ+6/9omX+IxzY1dBX+Z3oEB7mJy4hb97zSeNVfhEtIZ46fISIwcyaZyQlh3iYqOsJsvqwrTzG1mmMoV3gZwkgnzmUk2wNDyJWnR/ZrgyDJu3GsIViFAwYg4JsvAQt0zdbi4FAZ/f2jhHzhfSv8Suotjc/aFBDIjh7HywAqa0uAHvwUKcStlbaURxuqYX3FE6rGZp1nCC06EO4LjajvOM03LxHpNOZz6KQY8g0S2vpMuByOhsuU55E/bIj7qUH3JUpmqoX2WteO64/dVwLJCkFkUAv8TP2QJyApqFDWINUewHhgwVGTD3v4syBv9r1SXf6yDecaeffI1dUWyznMtcXPfkAfbeZYhiKNh54JTRrR65/DmVVqbsS9rXikXBy15NnkSjJ30P4sq1NRPQRyWLwpo4cYvjmrtFaNcD+U1SRBfKZsF1XYbNepVUyensfpm2ElhKZqXJGTDRldhxOLTCZMh+PNA=
